---
name: CI - Testing | Action
'on':
  push:

jobs:

  bundler-audit:
    name: Bundler Audit
    runs-on: ubuntu-latest

    steps:
      - name: Step -> Install dependencies
        run: |
          sudo apt-get install -y \
            build-essential \
            curl \
            libcurl4-openssl-dev \
            libfontconfig \
            libfreetype6 \
            libx11-6 \
            libxext6 \
            libxml2-utils \
            libxrender1 \
            xz-utils \
            zlib1g &&
          curl -L -o wkhtmltopdf.tar.xz https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz &&
          tar -xf wkhtmltopdf.tar.xz &&
          sudo mv wkhtmltox/bin/wkhtmltopdf /usr/local/bin/wkhtmltopdf &&
          sudo chmod +x /usr/local/bin/wkhtmltopdf

      - name: Step -> Checkout code
        uses: actions/checkout@v3

      - name: Step -> Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Step -> Bundler Audit
        run: |
          bundle exec bundler-audit update
          bundle exec bundler-audit
